version: 0.2

env:
  variables:
    S3_BUCKET_NAME: "todo-frontend1"
    AWS_REGION: "us-east-1"  # Change this to your desired region
    FRONT_END_DIR: "build"   # This is the default build output for React, change if different

phases:
  install:
    runtime-versions:
      nodejs: 20  # Specify Node.js version (use the version that your app uses)
    commands:
      - echo Installing dependencies...
      - npm install  # Install the dependencies for your front-end app

  build:
    commands:
      - echo Building the application...
      - npm run build  # This builds your app into the 'build' directory

  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync ./build/ s3://todo-frontend1 --delete

artifacts:
  files:
    - '**/*'  # Include all files in the output directory
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'  # Cache node_modules for faster builds
